version: '3.8'

services:
  bot:
    build: .
    container_name: entschuldigungsformular-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DATABASE_URL=sqlite:///data/bot.db
      - DEBUG=True
      - LOG_LEVEL=INFO
      - PORT=8000
    volumes:
      - ./output:/app/output
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: PostgreSQL für lokale Entwicklung
  postgres:
    image: postgres:15-alpine
    container_name: entschuldigungsformular-postgres
    environment:
      - POSTGRES_DB=entschuldigungsformular
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=botpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
